#!/usr/bin/env bash
# Installs nginx on server web-01
# server listens on port 80
# returns a page with string hello world
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
mkdir -p /var/www/html
chmod -R 755 /var/www
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
