#!/usr/bin/env bash

sudo apt-get -y  update
sudo apt-get -y install nginx

# starting nginx service
sudo service nginx start

echo "allowing nginx on firewall"
sudo ufw allow 'Nginx HTTP'

echo "Give the user ownership to website files for easy editing"
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Backup default index"
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo "Creating new index"
echo -e "Hello World!" >> /var/www/html/index.nginx-debian.html

echo "Restarting nginx"
sudo service nginx restart

