#!/usr/bin/env bash
# Script that modifies nginx config
# for a redirection
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sudo service nginx restart
