#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
# firewall config
sudo ufw allow 1344
sudo ufw enable
MyConfig="\
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend web-servers
    
backend web-servers
    balance roundrobin
    server 16641-web-01 3.239.98.245:80
    server 16641-web-02 34.239.177.244:80
"
# change ownership
sudo chown -R "$USER":"$USER" /etc/haproxy
sudo chmod -R 755 /etc/haproxy

sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt update
sudo apt install -y haproxy
sudo echo "$MyConfig" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
