#!/usr/bin/env bash
# use mysql_dump  to create archive files for backup
# Generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
