#!/usr/bin/env bash
# a Bash script that configures a server to the above requirements
rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-enabled/default  /etc/nginx/sites-enabled/default
sudo service nginx restart

